### ISSUE TITLE
Why the result of W1 visualization has the same shape with input 

### ISSUE THREAD

**Issue by Cli98** [xhp-hust-2018-2011/S-DCNet#11]
Hi @xhp-hust-2018-2011 @poppinace 

Please allow me to ask, in your paper section 3.2 and in your code, W1 has the same size of C1 with a shape of (2,2), where in your Section 5.2(Figure 8), the input crop seems have the same size compared with W1 visualization.

Is this W1 in section 5.2 the same as W1 in section 3.2? If yes, why could they have the same size? How you visualize W1 in this case?

**Comment by xhp-hust-2018-2011** [comment]
Each element of W_1 denotes whether to divide the corresponding local area in the input image. We can assign the corresponding local area in the input image with the corresopnding element in W_1.

**Comment by xhp-hust-2018-2011** [comment]
W1 in section 5.2 has the same as W1 in section 3.2. The visualization method is listed above.

**Comment by Cli98** [comment]
Thank you!
