### ISSUE TITLE
How to integral over array

### ISSUE THREAD

**Issue by Cli98** [xhp-hust-2018-2011/S-DCNet#12]
In algorithm 1, the paper mentioned "Integrate over DIV_N to obtain the image count C". How to integrate over DIV_N(an array)? Any reference?

**Comment by xhp-hust-2018-2011** [comment]
In our implemention, it is the sum of DIV_N. You can find it at "Val.py" line 48, "pre =  (outputs).sum()".

**Comment by Cli98** [comment]
Great. I do appreciate your help
